apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: my-three-tier-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: your-nodejs-app-image:latest
